### ISSUE TITLE
tests fail when tracing feature is enabled but pyo3 feature is not.

### ISSUE THREAD

**Issue by plugwash** [konstin/pep508_rs#18]
cargo test --features tracing

Gives me

    ---- marker::test::warnings stdout ----
    thread 'marker::test::warnings' panicked at src/marker.rs:1440:30:
    index out of bounds: the len is 0 but the index is 0
    note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace

---

    cargo test --all --all-targets --features tracing,pyo3

Passes.

I do not understand the code well-enough to know if this is just an issue with the feature guards on the test, or if it is indicative of a deeper problem.

**Comment by konstin** [comment]
I've removed the pyo3 bindings, they should live in a separate crates if they are still needed
