### ISSUE TITLE
AST access?

### ISSUE THREAD

**Issue by jelmer** [konstin/pep508_rs#21]
Unless I've missed something, recent versions of pep508-rs have made it impossible to traverse parsed expressions and e.g. work out what the minimum python version is. From what I can tell, it's just possible to evaluate whether an expression matches certain conditions.

Is there any change AST access could be brought back, or am I perhaps misreading the API?

**Comment by jelmer** [comment]
Background: I'm using pep508-rs to convert python requirement expressions to e.g. Debian package dependency expressions.

**Comment by konstin** [comment]
The new markers use Algebraic Decision Diagrams (ADD) for better performance and don't preserve the parsed AST. `MarkerTree::to_dnf` may contain the information you need.

**Comment by jelmer** [comment]
Thanks for the pointer to ``to_dnf``, that gives me what I was looking for.
