### ISSUE TITLE
`Requirement` `Display` normalization for white-spaces

### ISSUE THREAD

**Issue by cnpryer** [konstin/pep508_rs#5]
Hi! Thanks for all the work on these PEP implementations. Happy to help where I can.

I noticed between the PEP440 implementation and this one you're opting for including white-spaces in the specifiers' `Display`. Any thoughts on normalizing this to remove white-spaces?

PEP440 makes spaces optional, but IME the normalization to remove white-spaces seems like a better option for something core like the `Requirement` to include. Maybe I'm missing something though.

**Comment by konstin** [comment]
i don't have a strong opinion on whitrspace; i have made some changes on pep440_rs main (https://github.com/konstin/pep440-rs/commit/3ba82d9d6e850dada4741b0315f2db36d6bd5cf2) though to make the whitespace look more like poetry's which would be convenient for me)

**Comment by cnpryer** [comment]
Gotcha. I can't think of a good reason to go either way besides readability (with spaces). Figured I'd ask since I was curious. IIRC `pip` normalizes them to remove white-spaces, but don't quote me on that.

I'll be playing around a lot with this stuff, so if anything comes up that makes sense to surface here I'll open a new issue.

Thanks for the response :)
